apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: todolist
        - name: POSTGRES_USER
          value: abchini
        - name: POSTGRES_PASSWORD
          value: Oodrive01
       